{"trial_id": "0001", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "input_units", "default": null, "conditions": [], "min_value": 32, "max_value": 512, "step": 32, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_layers", "default": null, "conditions": [], "min_value": 1, "max_value": 5, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "layer_0_units", "default": null, "conditions": [], "min_value": 32, "max_value": 256, "step": 32, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.01, "conditions": [], "values": [0.01, 0.001, 0.0001], "ordered": true}}, {"class_name": "Int", "config": {"name": "layer_1_units", "default": null, "conditions": [], "min_value": 32, "max_value": 256, "step": 32, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "layer_2_units", "default": null, "conditions": [], "min_value": 32, "max_value": 256, "step": 32, "sampling": "linear"}}], "values": {"input_units": 416, "num_layers": 3, "layer_0_units": 96, "learning_rate": 0.01, "tuner/epochs": 2, "tuner/initial_epoch": 0, "tuner/bracket": 1, "tuner/round": 0, "layer_1_units": 32, "layer_2_units": 32}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py\", line 574, in safe_patch_function\n    patch_function.call(call_original, *args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py\", line 165, in call\n    return cls().__call__(original, *args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py\", line 176, in __call__\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py\", line 169, in __call__\n    return self._patch_implementation(original, *args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py\", line 227, in _patch_implementation\n    result = super()._patch_implementation(original, *args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/keras/autologging.py\", line 262, in _patch_implementation\n    history = original(inst, *args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py\", line 557, in call_original\n    return call_original_fn_with_event_logging(_original_fn, og_args, og_kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py\", line 492, in call_original_fn_with_event_logging\n    original_fn_result = original_fn(*og_args, **og_kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py\", line 554, in _original_fn\n    original_result = original(*_og_args, **_og_kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/usr/local/lib/python3.10/site-packages/keras/src/utils/progbar.py\", line 162, in update\n    avg = backend.convert_to_numpy(\nAttributeError: module 'keras.src.backend' has no attribute 'convert_to_numpy'\n"}